local remapper = require('custom.remapper')

remapper.add_remap("n", "<leader>w", ":w<CR>", "Save file", { "File Management" })
remapper.add_remap("n", "<leader>q", ":q<CR>", "Quit Neovim", { "File Management" })
remapper.add_remap("n", "<leader>f", ":Telescope find_files<CR>", "Find files", { "Search" })

remapper.add_remap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<cr>', 'Hover', { 'LSP' })
remapper.add_remap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<cr>', 'Go to definition', { 'LSP' })
remapper.add_remap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<cr>', 'Go to declaration', { 'LSP' })
remapper.add_remap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<cr>', 'Go to implementation', { 'LSP' })
remapper.add_remap('n', 'go', '<cmd>lua vim.lsp.buf.type_definition()<cr>', 'Type definition', { 'LSP' })
remapper.add_remap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<cr>', 'Go to references', { 'LSP' })
remapper.add_remap('n', 'gs', '<cmd>lua vim.lsp.buf.signature_help()<cr>', 'Signature help', { 'LSP' })
remapper.add_remap('n', '<F2>', '<cmd>lua vim.lsp.buf.rename()<cr>', 'Rename', { 'LSP' })
remapper.add_remap({ 'n', 'x' }, '<F3>', '<cmd>lua vim.lsp.buf.format({async = true})<cr>', 'Format', { 'LSP' })
remapper.add_remap('n', '<F4>', '<cmd>lua vim.lsp.buf.code_action()<cr>', 'Code actions', { 'LSP' })
